version: 'v1'

services:
  app: 
  # local do dockerFile
    build: .
    command: wait-for db:3306 -t 40 -- ./start.sh
    ports:
      - 8000:3000 # maquina:container
    volumes:
      - .:/home/node/app # manda tudo do diretorio da esquerda para o da direita dentro do container
      # - /home/node/app/node_modules # volume anônimo
    environment:
      - name=value
    depends_on:
      - db
  db: 
    image: mysql:5.7
    environment: 
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root # logar bash mysql -uroot -proot  -- visualizar dbs -> show databases;
    volumes:
      - ./dbdata:/var/lib/mysql

  # docker compose up || docker compose up -d --build
  #docker compose stop
  # docker compose ps --- listar containers
  # docker compose exec app bash || sh --- dependendo da imagem 
# docker compose down
#PRINTENV mostrar variaveis do linux