FROM node:14.17.0-slim

# cria diretorio dentro do container
WORKDIR /home/node/app

COPY package*.json ./

USER node

RUN yarn install

COPY . .

# executado no momento em que foi gerado, comando pro container ficar em pé
CMD [ "node", "/home/node/app/index.js" ]

# docker build -t USUARIODOCKERHUB/minha-imagem-producao-node . -f Dockerfile.prod

# docker push USUARIODOCKERHUB/minha-imagem-producao-node